### ISSUE TITLE
Create tutorial/blogpost/vlogpost related to the feature

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/core-document-synchronization#69]
This repo hasn't received any focus so far and is in need of some advertisement. Create an example on [branch knowledge](https://developer.qlik.com/knowledge), medium or similar platform to reach out to customers.

**Comment by peol** [comment]
We should probably rename it (to `core-app-sync` or similar) since `document` isn't the term we use any more.

Furthermore, the _preferred_ way of doing this is using NATS today, which is a feature not exposed in Qlik Core yet. I think that's a good discussion to have before we highlight the filepolling mechanism more.

**Comment by sublibra** [comment]
WON'T DO: Repository archived
